### ISSUE TITLE
Blank icon and unclear delete icon

### ISSUE THREAD

**Issue by roadrunner56** [EndlessSkyCommunity/ESLauncher2#111]
OS: Kubuntu 20.04 
There appears to be a blank icon in the launcher. Hovering over it implies that there is a button in the space, but when clicked on, nothing happens. In addition, it is not clear that the red button deletes an instance; when I first started using ESL, I accidentally deleted an instance trying to figure out what the button did. 
Here's a picture of the phantom icon:
![Screenshot_20210114_114424](https://user-images.githubusercontent.com/65418682/104637302-dd53b880-5661-11eb-848f-3d13475b7e21.png)

As for the red button, perhaps it could be replaced with a garbage can icon, or maybe a tooltip could be used to make its purpose clearer. 
Thanks for the work you've done on this project btw, it makes using continuous a lot easier for me.

**Comment by MCOfficer** [comment]
The red button is a trashcan icon, but it seems that there's not enough space to render it. The blank button is the update button, and i have no idea why that icon isn't showing.

For reference: 
![image](https://user-images.githubusercontent.com/22377202/104637851-9f788380-56a5-11eb-8945-2de7d6edbf56.png)

For lack of a better idea, you could try resizing the window..

**Comment by roadrunner56** [comment]
I moved my taskbar from the side to the bottom, which gave the buttons a little extra space. I can see a little bit of the update button now, but the folder icon is still hidden. My screen has a resolution of 1366x768, if that helps. I also forgot to mention that I'm on v. 0.6.1. Thanks for your quick reply!

**Comment by MCOfficer** [comment]
Damn, it is the screen size. I didn't account for screens that small... Not sure how much effort i want to sink into this. maybe i'll just lower the font size of the instance name.

**Comment by MCOfficer** [comment]
It's a lazy patch, but can you try [this build](https://github.com/EndlessSkyCommunity/ESLauncher2/actions/runs/487649036)? artifacts are at the bottom of the page.

Using a shorter instance name will also help.

**Comment by roadrunner56** [comment]
Will the build also fix the corrupt message that tyro was talking about in the discord? Also, is it possible to rename instances, and if so, how? Thanks for your help.

**Comment by MCOfficer** [comment]
I have not been able to reproduce that issue, so i have no clue. Instances can't be renamed, but you can delete and reinstall them without data loss (your save files are in a completely different directory)

**Comment by roadrunner56** [comment]
So I installed it and it sort of fixed it. When I moved my taskbar to the bottom, I could see all the buttons, but the trash icon was still a red bar:
![Screenshot_20210115_090945](https://user-images.githubusercontent.com/65418682/104750612-91f8e300-5711-11eb-9dcf-4cb00449b60f.png)

I usually have my taskbar to the side though, and in that configuration, it's still pretty squashed.

**Comment by MCOfficer** [comment]
I could start messing around with layouts now, but honestly i'd just recommend you to use the short commit has as name and call it a day.

**Comment by roadrunner56** [comment]
I'm rather new to github and ESL, would simply typing in [e0ae8bf](https://github.com/endless-sky/endless-sky/commit/e0ae8bf871f4ec957075e052cb1d0976d5a0de63) install it? I'm really sorry about this if this whole thing could've been solved with just typing in a different name. Again, thanks so much.

**Comment by MCOfficer** [comment]
I just used the short hash as example because i thought you wanted to name your instances after their commit hashes. (It's common practice to use the first X letters of a hash to represent that, just like github did in your last comment).

You still have to enter the exact hash (i *think*, maybe github is being courteous) as version, but the name can be literally anything you want. So just use something that's a bit shorter for that.


![image](https://user-images.githubusercontent.com/22377202/104751546-d5754080-5755-11eb-90ae-4b529de7bb17.png)

**Comment by roadrunner56** [comment]
I tried doing that, but it gave me the error message "Install failed: Failed to read JSON: missing field 'id' at line 1 column 116". 
![Screenshot_20210115_100311](https://user-images.githubusercontent.com/65418682/104757146-ebfda680-5719-11eb-8631-20aa373bbbfe.png)

**Comment by MCOfficer** [comment]
a shit, now i see my mistake... I'll file a new issue for that, until then use a commit has that starts with a number... *leaves in shame*
