### ISSUE TITLE
versions can falsely be prefixed with v

### ISSUE THREAD

**Issue by MCOfficer** [EndlessSkyCommunity/ESLauncher2#115]
as per #111 

![image](https://user-images.githubusercontent.com/22377202/104758518-dbbbea80-575e-11eb-8247-7499f35fb59b.png)

This tried to access `vCOMMIT_HASH`, which is obviously bullshit.

**Comment by roadrunner56** [comment]
I have no idea how to code, so I don't know if this helps, but I chose continuous and just entered in 'e0ae8bf' as the name and it installed fine. I can see all of the buttons now. 
![Screenshot_20210115_105531](https://user-images.githubusercontent.com/65418682/104761493-371ab800-5720-11eb-9fc7-afae8262552e.png)

**Comment by MCOfficer** [comment]
> I have no idea how to code, so I don't know if this helps, but I chose continuous and just entered in 'e0ae8bf' as the name and it installed fine. I can see all of the buttons now.

The name has no impact on what is being installed, only the version field does.

When you select release, the program tries to prefix your input with a `v` (so you can enter `0.9.12` and it will still be correct). Unfortunately this also seems to apply to commit hashes for some reason, who *definitely don't* need a prefix :D
