### ISSUE TITLE
PR doesn't work due to double .zip ending

### ISSUE THREAD

**Issue by pega3** [EndlessSkyCommunity/ESLauncher2#12]
Currently the PR function doesn't work because it adds a duplicate .zip ending. 

[ESLauncher2.log](https://github.com/EndlessSkyCommunity/ESLauncher2/files/4751345/ESLauncher2.log)

**Comment by MCOfficer** [comment]
The double-zip is intended - Github Actions upload the release (which is a zip) into a sort-of file repository. Downloading the repository results in a zip file containing the release- zip file.

However, i'm puzzled as to why it didn't manage to extract the inner zip file. Which PR did you download - was it endless-sky/endless-sky#5119 by chance?

**Comment by pega3** [comment]
No, I tested with #5112. I believe the reason it was not able to unzip is that the file was only zipped once, but it attempted to unzip a second time, which consequently failed.
