### ISSUE TITLE
Continuous build opens with a cmd window

### ISSUE THREAD

**Issue by MCOfficer** [EndlessSkyCommunity/ESLauncher2#136]
On windows, launching the continuous build opens a cmd shell alongside the game. Closing the cmd also shuts down the game. Nothing unusual in the logs

May be an issue with the continuous build itself, or with the way ESL2 launches it.

**Comment by tehhowch** [comment]
The game attempts to initialize a console when launched from a console context in Windows. That behavior isn't going to go away (there's no other stdout option). There may be a way for ESL2 to provide a console display for the game, which would perhaps prevent this.

**Comment by MCOfficer** [comment]
How is a console context detected?

**Comment by tehhowch** [comment]
> How is a console context detected?

However Windows does it 🙃

@comnom provided the implementation in https://github.com/endless-sky/endless-sky/pull/4249

**Comment by MCOfficer** [comment]
I see... so it checks if stdout, stderr *and* stdin are a file or some form of stream. if any of them aren't, it opens the console. 

What's weird is that i can't make this work in ESL2.
```rs
        cmd.stdin(Stdio::piped()).stderr(Stdio::piped()).stdout(Stdio::piped()).output()
```

But if i pipe all those things in git-bash, no console opens
```
$ echo "" | ./EndlessSky.exe 1>test.log 2>test2.log
```

**Comment by MCOfficer** [comment]
Haaaang on. That InitConsole function is only called *when ES has any kind of arguments*. It doesn't get called when ES is started via ESL2.

**Comment by MCOfficer** [comment]
Could it be that the make build doesn't use `-Wl,-subsystem,windows` anymore? (or perhaps never used it)?

**Comment by tehhowch** [comment]
Yeah, that's the issue.

**Comment by MCOfficer** [comment]
Thanks!

Also, you can close issues across repos and even orgs? neat.

**Comment by tehhowch** [comment]
Yeah, that was new to me. I believe because I have the appropriate access, it was allowed 🤷
