### ISSUE TITLE
Update of Continous build not working

### ISSUE THREAD

**Issue by pega3** [EndlessSkyCommunity/ESLauncher2#2]
OS: Win10-64
ESLauncher2-Version: 0.4.1

To reproduce: 
- installed continous build (into "cont" instance) - worked like a charm
- closed tool
- started tool again and pushed the update button
Error message: [ERROR] Failed to update instance: C:\...\ESLauncher2\instances\cont\EndlessSky-win64 doesn't exist 
(I shortended the path, full path in log)

[ESLauncher2.log](https://github.com/EndlessSkyCommunity/ESLauncher2/files/4737329/ESLauncher2.log)

I would guess this is related to the other issue I reported.

**Comment by MCOfficer** [comment]
Should be fixed by 265e7101f08fb06c8be0853fd4301e19fccdf38c.

Please try the builds from https://github.com/EndlessSkyCommunity/ESLauncher2/actions/runs/126222570.

**Comment by pega3** [comment]
I can confirm that the issue is fixed. Now worked fine on my machine
