### ISSUE TITLE
Support load by URL

### ISSUE THREAD

**Issue by samrocketman** [EndlessSkyCommunity/ESLauncher2#272]
Sometimes I might make a branch on my fork (not a pull request to endless sky) which has multiple PRs combined for people to play test an entire suite of changes.  It would be cool if a generic GitHub URL was supported for branches, pull requests, and tags.

The GitHub URL could support the following three syntax formats (branch, tag, PR).

```
https://github.com/endless-sky/endless-sky/tree/master/
https://github.com/endless-sky/endless-sky/tree/v0.9.14
https://github.com/endless-sky/endless-sky/pull/6669
```

The point of supporting a generic URL is let's say I push a branch to my personal fork.  I could then provide a URL such as:

```
https://github.com/samrocketman/endless-sky/tree/mining-complete
```

And then users would be able to use ESLauncher to download my custom version which combines multiple pull requests.

**Comment by MCOfficer** [comment]
Also #172
