### ISSUE TITLE
Plugin feature reports system files as installed plug-ins

### ISSUE THREAD

**Issue by pega3** [EndlessSkyCommunity/ESLauncher2#32]
User Darcy Manoel reported that on MacOS the system file ".DS_Store" gets reported as an installed plug-in. 
Ideally, the launcher filters out typical system files and ignores them in the plugin directory.

**Comment by MCOfficer** [comment]
idk about system files but we can just filter files to begin with.

**Comment by pega3** [comment]
In theory, only valid directories should be reported. So, I wonder why this happened. If the launcher can't be restricted to directories, the following files should probably be ignored:
MacOS:
.DS_Store
.localized

Windows:
desktop.ini
Thumbs.db

In general:
.gitignore
sync.ffs_db

**Comment by MCOfficer** [comment]
upstream https://github.com/EndlessSkyCommunity/espim/issues/2

**Comment by MCOfficer** [comment]
#37
