### ISSUE TITLE
Hard drive gets error spam when computer is awoken with ship in space

### ISSUE THREAD

**Issue by ziproot** [EndlessSkyCommunity/ESLauncher2#326]
The following text sometimes gets spammed into my hard drive with eslauncher2 open.
```
an error occurred on output stream: A backend-specific error has occurred: ALSA function 'snd_pcm_writei' failed with error 'ESTRPIPE: Streams pipe error'
```
Closing eslauncher2 instantly stops my hard drive from getting eaten. It seems to happen when I am in a battle and have boarded a ship, but I cannot confirm that it only happens then.

**Comment by MCOfficer** [comment]
So - does it originate from ESLauncher or from endless sky? which logfile is being spammed exactly?

**Comment by ziproot** [comment]
The log file being spammed is `.xsession-errors`
It originates from ESLauncher as my space continued to be taken up when endless sky was closed but not ESLauncher2, then stopped when ESLauncher2 was closed. It seems to happen in debug mode only. I had the default state for ESLauncher's music, and my sound was muted if that helps.

**Comment by ziproot** [comment]
OK, I have some updates:
-I have ESLauncher 2 v0.8.6 open and it is indeed printing the same line to `.xsession-errors`
-Endless Sky is not open.
-This issue persisted regardless of whether or not ESLauncher2's music was playing.
-This issue persisted regardless of whether or not my sound was muted.
-Closing ESLauncher 2 fixed the issue and it stopped being written to. Reopening it did not make the issue reappear immediately, but the problem resumed after some time. I am currently testing to see if it's an issue with Endless Sky by only having ESLauncher2 open. If the error resumes while this is the case, then the problem is with ESLauncher2.
-I currently have a workaround where I have a cronjob running that purges the file if it gets too large, but this is slowing down my computer.

**Comment by MCOfficer** [comment]
Does it perhaps coincide with the song restarting?

**Comment by ziproot** [comment]
If I open eslauncher2 from command line, this error is instead spammed to terminal after some time. I think it may have to do with putting my computer to sleep; I will check again.

**Comment by MCOfficer** [comment]
I'm still not entirely clear if this is ESLauncher2's music systems (which doesn't lign up with the "ship in space" part, since ESL2 cannot even know that), or if it's ES. Can you try and reproduce that by starting ES not through ESL2, but via the terminal?

**Comment by ziproot** [comment]
I was unable to reproduce the bug when starting from terminal.

**Comment by MCOfficer** [comment]
But the documentation is talking about audio streams, no? there's no audio stream from ES to the launcher, it should interface with ALSA directly. But in that case you should be able to reproduce it with the terminal...

**Comment by ziproot** [comment]
OK, I tried to make a video demonstrating the error, and this makes even less sense now.
Endless Sky on terminal (direct) vs terminal (eslauncher2), suspending from menu:
https://user-images.githubusercontent.com/109186806/216794376-ceb778f5-c164-486e-a2c2-a4e8bbe3b2f9.mp4
No issue either time
Endless Sky on terminal (direct) vs terminal (eslauncher2), suspending by closing lid:
https://user-images.githubusercontent.com/109186806/216795720-fb0eefdf-ec91-4a8b-8428-68efe15f1351.mp4
Issue only for eslauncher2

**Comment by ziproot** [comment]
The initial bug may still be present in systems running LXQt, however, I will be unable to verify it any longer as I have upgraded my operating system and now use KDE. I will therefore close this bug as not planned for now and re-open it if I find that this issue persists.
