### ISSUE TITLE
Can't run on zorin os 16.2

### ISSUE THREAD

**Issue by Ranko-Saotome** [EndlessSkyCommunity/ESLauncher2#337]
./eslauncher2-x86_64-unknown-linux-gnu.sh: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./eslauncher2-x86_64-unknown-linux-gnu.sh)
./eslauncher2-x86_64-unknown-linux-gnu.sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./eslauncher2-x86_64-unknown-linux-gnu.sh)
./eslauncher2-x86_64-unknown-linux-gnu.sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./eslauncher2-x86_64-unknown-linux-gnu.sh)
./eslauncher2-x86_64-unknown-linux-gnu.sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./eslauncher2-x86_64-unknown-linux-gnu.sh)

**Comment by MCOfficer** [comment]
Update from discord: zorin 16.2 is based on 20.04, so we can support this by dropping the pipeline down from latest.

**Comment by Ranko-Saotome** [comment]
thanks
