### ISSUE TITLE
Improvement: retain audio settings

### ISSUE THREAD

**Issue by pega3** [EndlessSkyCommunity/ESLauncher2#34]
Currently, the application does not remember that I paused the audio when a game that I have launched exits.
To reproduce:
- Run ESLauncher2
- Pause Audio
- Launch Endless Sky game
- Exit game
=> Launcher will play music again. 
It should retain the setting before the launch, i.e. if I paused the music, it should not start playing again. 

To take this a stop further, ESLauncher2 could as well retain this setting between executions of ESLauncher2 itself. But that would mean the state has to be persisted.

**Comment by MCOfficer** [comment]
Let's keep it simple for now and do the rest after #35

**Comment by MCOfficer** [comment]
f2e3d030356e73f8ed5d30bff2708de3a4e34d83
