### ISSUE TITLE
launching instance fails "UTC offset could not be determined"

### ISSUE THREAD

**Issue by wararjey** [EndlessSkyCommunity/ESLauncher2#374]
Hello,

I am using the eslauncher2 aur build on an Arch Linux system.

I could successfully build, install eslauncher2.

I could successfully run eslauncher2 to download an instance.

However, trying to launch the instance fails, eslauncher2 prints the following error message in the log:

`The system's UTC offset could not be determined`

Launching the downloaded appimage manually works, though.

Regards,

**Comment by MCOfficer** [comment]
*should* be fixed with 0.9.1: 3e35e8318c261920e14800946d18fe2dedcea7a4

**Comment by quyykk** [comment]
I had the same issue, and v0.9.2 works for me now :smile:

**Comment by wararjey** [comment]
Yup, works for me now. Thank You :-)
