### ISSUE TITLE
Window doesn't open

### ISSUE THREAD

**Issue by MCOfficer** [EndlessSkyCommunity/ESLauncher2#4]
This is a tracking issue for all of these symptoms - mostly to have a #wontfix i can point to.

ESLauncher2 uses [iced](https://github.com/hecrj/iced/) as GUI toolkit - which uses the [wgpu-stack](https://github.com/gfx-rs/wgpu-rs) as rendering backend.

Most of these issues presumably originate from these components. There's a simple way to test that - go to [iced's github actions](https://github.com/hecrj/iced/actions?query=workflow%3ABuild) and download the latest "todo" program. If it doesn't work, blame iced / wgpu, otherwise open a new issue.

See also https://github.com/hecrj/iced/issues/337.

---

Update: There is a branch with iced's new OpenGL-based backend. You can try it out here: <https://github.com/EndlessSkyCommunity/ESLauncher2/actions/runs/352405978>

**Comment by MCOfficer** [comment]
Should be fixed with 0.6.0.

**Comment by georgelemental** [comment]
It works! There are 2 minor issues though: plugin images aren't visible (mentioned in release notes) and text is a bit blurry (esp. the small gray-on-white text).

**Comment by MCOfficer** [comment]
Iced has a fallback software-renderer based on tiny-skia now, so we should be completely dependency free on the graphics side.
