### ISSUE TITLE
[Enhancement] Add support local images

### ISSUE THREAD

**Issue by xobes** [EndlessSkyCommunity/ESLauncher2#474]
Would it be possible to support local installs as well (e.g. in development with plugins?)

I hacked it into the .json file but it's not beautiful, and I don't even really know the utility of it yet.  Thoughts?

I think a more polished approach would be to add a new "type" of "Local" and not display the download button in that case, rather an edit button to configure the paths and values.

![Screenshot from 2024-10-30 09-40-59](https://github.com/user-attachments/assets/db1f7e84-d4e8-4785-94ab-a562f01632c7)

**Comment by MCOfficer** [comment]
Sounds like a lot of effort for relatively little benefit.

**Comment by xobes** [comment]
Fair.  I don't know Rust, so I do agree with it being more effort than worth.  Was a suggestion, thanks for looking.
