### ISSUE TITLE
Installing an instance with "/" in the name causes subfolder to be created

### ISSUE THREAD

**Issue by calniotrey** [EndlessSkyCommunity/ESLauncher2#75]
Experimented on Windows 10, latest release
I tried to create a continuous instance of ES name "Continuous 9/10/20" and it created "Continuous 9" with subfolder "10" with subfolder "20". The data was inside the last one iirc
Didn't try to launch, but deleted it (using the delete button on the launcher). It deleted the last folder (the "20") but not the rest.

**Comment by Zitchas** [comment]
Yeah, using `/` in the names of instances, github branches, etc leads to problems.
